accounts/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^login/$', 'accounts.views.login', name='login'),
    url(r'^logout/$', 'accounts.views.logout', name='logout')
)

student/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^$', 'student.views.index', name='index'),
    url(r'^$', 'student.views.tasks', name='tasks'),
    url(r'^$', 'student.views.docs', name='docs'),
)

virtual_school/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from virtual_school import settings

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^student/', include('student.urls', namespace='student')),
    url(r'^teacher/', include('teacher.urls', namespace='teacher')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^$', 'accounts.views.login')
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

accounts/models.py
# -*- coding: utf-8 -*-
from django.db import models

# Create your models here.

accounts/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect
from django.core.context_processors import csrf
from django.contrib import auth

from customuser.models import CustomUser
from school.models import Teacher, Student


def login(request):
    args = {}
    args.update(csrf(request))
    if request.POST:
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None:

            cast = user.cast()

            if type(cast) is Student:
                auth.login(request, user)
                return redirect('student:index')

            elif type(cast) is Teacher:
                auth.login(request, user)
                return redirect('teacher:index')

            else:
                args['has_error'] = True
                args['error'] = u'Данная форма авторизации предназначена только для учеников и преподавателей'
                return render(request, 'accounts/login.html', args)
        else:
            args['has_error'] = True
            args['error'] = u'Не вернео имя пользователя или пароль'
            return render(request, 'accounts/login.html', args)
    else:
        return render(request, 'accounts/login.html', args)


def logout(request):
    auth.logout(request)
    return redirect('/')

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Авторизация{% endblock %}

{% block css %}
<link href="{% static 'css/login.css'%}" rel="stylesheet">
{% endblock %}

{% block body %}

  <div class="container">

    {% if has_error %}
      <p class="alert alert-danger">{{ error }}</p>
    {% endif %}

    <form class="form-signin" role="form" method="post" action="{% url 'accounts:login' %}">
      {% csrf_token %}
      <h2 class="form-signin-heading">Авторизация</h2>
      <input type="text" class="form-control" placeholder="имя пользователя" required autofocus
          name="username" id="username">
      <input type="password" class="form-control" placeholder="пароль" required
          name="password" id="password">
  {#    <label class="checkbox">#}
  {#      <input type="checkbox" value="remember-me"> Remember me#}
  {#    </label>#}
      <button class="btn btn-lg btn-primary btn-block" type="submit">Вход</button>
    </form>
  </div> <!-- /container -->
{% endblock %}