student/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^$', 'student.views.index', name='index'),
    url(r'^$', 'student.views.tasks', name='tasks'),
    url(r'^$', 'student.views.docs', name='docs'),
)

virtual_school/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from virtual_school import settings

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^student/', include('student.urls', namespace='student')),
    url(r'^teacher/', include('teacher.urls', namespace='teacher')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^$', 'accounts.views.login')
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

student/models.py
from django.db import models

# Create your models here.

student/views.py
# -*- coding: utf-8 -*-
from django.utils import timezone
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from school.models import Student


def student_required(function):
    def wrapper(request, *args, **kw):
        cast = request.user.cast()
        if type(cast) is Student:
            request.student = cast
            return function(request, *args, **kw)
        else:
            return redirect('accounts:logout')
    return wrapper


@login_required
@student_required
def index(request):
    args = {
        'request': request,
        'student': request.student,
        'tasks': request.student.task_set.filter(release_date__gte=timezone.now())
    }
    return render(request, 'student/index.html', args)


@login_required
@student_required
def tasks(request):
    pass


@login_required
@student_required
def docs(request):
    pass

student/templates/student/base.html
{% extends 'base_site.html' %}

{% load staticfiles %}

{% block css %}
  {{ block.super }}
  <link href="{% static 'student/css/common.css' %}" rel="stylesheet">
{% endblock %}

{% block home_url %}{% url 'student:index' %}{% endblock %}

{% url 'student:tasks' as tasks_url %}
{% url 'student:docs' as docs_url %}

{% block navbar %}
<li><a href="#" {% if request.get_full_path == tasks_url %}class="active"{% endif %}>Задания</a></li>
<li><a href="#" {% if request.get_full_path == docs_url %}class="active"{% endif %}>Справочная литература</a></li>
{% endblock %}

student/templates/student/index.html
{% extends 'student/base.html' %}

{% block content %}

<h2>{{ student.get_full_name }}</h2>

<div id="tasks">
  <h4>Ближайшие задания</h4>
  <ul class="list-group">
  {% for task in tasks %}
    <li class="list-group-item">{{ task.text|safe }} - {{ task.release_date }}</li>
  {% endfor %}
  </ul>
</div>

{% endblock %}