accounts/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^login/$', 'accounts.views.login', name='login'),
    url(r'^logout/$', 'accounts.views.logout', name='logout')
)

student/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^$', 'student.views.index', name='index'),
    url(r'^$', 'student.views.tasks', name='tasks'),
    url(r'^$', 'student.views.docs', name='docs'),
)

virtual_school/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from virtual_school import settings

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^student/', include('student.urls', namespace='student')),
    url(r'^teacher/', include('teacher.urls', namespace='teacher')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^$', 'accounts.views.login')
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
{#    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">#}

    <title>{% block title %}Виртуальная школа{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css %}{% endblock %}

{#    <!-- Just for debugging purposes. Don't actually copy this line! -->#}
{#    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->#}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    {% block body %}{% endblock %}
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'jquery/jquery-1.11.1.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    {% block scripts %}{% endblock %}
  </body>
</html>

templates/base_site.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block css %}
<link href="{% static 'css/base_site.css' %}" rel="stylesheet">
{% endblock %}

{% block body %}
<!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">{% block nav_title %}{% endblock %}</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% block home_url %}#{% endblock %}">{% block home_title %}Школа{% endblock %}</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% block navbar %}{% endblock %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'accounts:logout' %}">Выход</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- Begin page content -->
    <div class="container">
      {% block content %}{{ content_text }}{% endblock %}
    </div>

    <div id="footer">
      <div class="container">
        {% block footer %}{% endblock %}
      </div>
    </div>
{% endblock %}